FROM node:18-alpine

RUN mkdir -p /app

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# COPY next-config.js ./next-config.js

# COPY pages ./pages
# COPY public ./public
# COPY styles ./styles

COPY . /app

EXPOSE 3000

# CMD ["npm", "dev"]